"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files:
  [
    {
      "source": "/frontend/src/lib/i18n/locales/en.json",
      "translation": "/frontend/src/lib/i18n/locales/%locale%.json",
    },
  ]
