import { z } from "zod";

export const appContextSchema = z.object({
  configuredProviders: z.array(z.string()),
  disableContinue: z.boolean(),
  title: z.string(),
  genericName: z.string(),
  domain: z.string(),
  forgotPasswordMessage: z.string(),
  oauthAutoRedirect: z.enum(["none", "github", "google", "generic"]),
  backgroundImage: z.string(),
  loginTitle: z.string().optional(),
  loginSubtitle: z.string().optional(),
  usernameTitle: z.string().optional(),
  passwordTitle: z.string().optional(),
  usernamePlaceholder: z.string().optional(),
  passwordPlaceholder: z.string().optional(),
  logo: z.string().optional(),
  logoSize: z.string().optional(),
  loginTitleSize: z.string().optional(),
  loginSubtitleSize: z.string().optional(),
  disableBorder: z.boolean().optional(),
  loginCardColor: z.string().optional(),
  loginTitleColor: z.string().optional(),
  loginSubtitleColor: z.string().optional(),
  usernameTextColor: z.string().optional(),
  passwordTextColor: z.string().optional(),
  googleButtonText: z.string().optional(),
  googleButtonTextColor: z.string().optional(),
  googleButtonBackgroundColor: z.string().optional(),
  googleButtonHideIcon: z.boolean().optional(),
  microsoftButtonText: z.string().optional(),
  microsoftButtonTextColor: z.string().optional(),
  microsoftButtonBackgroundColor: z.string().optional(),
  microsoftButtonHideIcon: z.boolean().optional(),
  githubButtonText: z.string().optional(),
  githubButtonTextColor: z.string().optional(),
  githubButtonBackgroundColor: z.string().optional(),
  githubButtonHideIcon: z.boolean().optional(),
  genericButtonText: z.string().optional(),
  genericButtonTextColor: z.string().optional(),
  genericButtonBackgroundColor: z.string().optional(),
  genericButtonHideIcon: z.boolean().optional(),
  loginButtonText: z.string().optional(),
  loginButtonTextColor: z.string().optional(),
  loginButtonBackgroundColor: z.string().optional(),
  disableLanguageSelector: z.boolean().optional(),
  favicon: z.string().optional(),
  backgroundColor: z.string().optional(),
  footerButtonText: z.string().optional(),
  footerButtonUrl: z.string().optional(),
  footerButtonNewTab: z.boolean().optional(),
  footerButtonTextColor: z.string().optional(),
  footerButtonBackgroundColor: z.string().optional(),
});

export type AppContextSchema = z.infer<typeof appContextSchema>;
